services:
  remnawave-subscription-page:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./backend/lte-template.txt:/opt/app/templates/lte-template.txt:ro
      - ./backend/wifi-template.txt:/opt/app/templates/wifi-template.txt:ro
      - ./backend/template-injector.yml:/opt/app/templates/template-injector.yml:ro
    ports:
      - '127.0.0.1:3010:3010'
